name: Build images

on:
  pull_request:
    types: [opened, reopened]
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/${{ github.repository_owner  }}/herald
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha        

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner  }}/herald:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner  }}/herald:buildcache,mode=max

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs:
      - build
    env:
      SERVER: https://api.paas.okd.cern.ch
      PROJECT: acts-herald
      APP_NAME: acts-herald
    steps:
      - name: Trigger redeploy
        run: >
          which sshpass
          && sshpass -p ${{ secrets.PWD }} ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@lxplus9.cern.ch 
          'oc login ${{ env.SERVER }} --token=${{ secrets.DEPLOY_TOKEN }}
          && oc project ${{ env.PROJECT }}
          && oc import-image ${{ env.APP_NAME }} --all'
